app/classroom/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, SelectField, IntegerField, DateField
from wtforms.validators import ValidationError, DataRequired, Length, NumberRange


class AddClassroomForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=4, max=100)])
    description = TextAreaField('Classroom Description', validators=[Length(min=0, max=140)])
    subject = SelectField('Subject', validators=[DataRequired()])
    term = StringField('Term', validators=[DataRequired(), Length(min=4, max=50)])
    year = IntegerField('Year', [DataRequired(), NumberRange(min=1900, max=2100)])
    time = StringField('Time', validators=[DataRequired(), Length(min=4, max=10)])
    active = BooleanField('Active')

    submit = SubmitField('Submit')


class AddStudentForm(FlaskForm):
    student = SelectField('Student Name', validators=[DataRequired()])
    submit = SubmitField('Add')


class AddStudentGradeForm(FlaskForm):
    grade = IntegerField('Grade', [DataRequired(), NumberRange(min=0, max=100)])
    date_occurred = DateField('Date Taken', format='%m/%d/%y')
    graded = BooleanField('Graded Item')
    comments = TextAreaField('Comments', validators=[Length(min=0, max=140)])
    coursework_item = SelectField('Coursework Item', validators=[DataRequired()])

    submit = SubmitField('Add Grade')

app/classroom/__init__.py
from flask import Blueprint

bp = Blueprint('classroom', __name__)

from app.classroom import routes

app/classroom/routes.py
from datetime import datetime
from flask import render_template, redirect, url_for, flash, request, current_app, jsonify
from flask_login import current_user, login_required

from app import db
from app.classroom import bp
from app.classroom.forms import AddClassroomForm, AddStudentForm, AddStudentGradeForm
from app.decorators import role_required
from app.models import Classroom, User, Subject, Role, Coursework, CourseworkInstance


@bp.route('/', methods=['GET'])
@bp.route('/<int:classroom_id>', methods=['GET'])
@login_required
def show_classroom(classroom_id=None):
    # Classroom for students
    _role = Role.query.filter_by(id=current_user.role_id).first()
    
    if _role.name == 'Student':
        if classroom_id:
            classroom = Classroom.query.filter_by(id=classroom_id).first()
            return render_template('classroom/classroom_detail.html', title=f'Classroom - {classroom.name}', classroom=classroom)
        page = request.args.get('page', 1, type=int)
        classrooms = Classroom.query.filter_by(creator_id=current_user.id).paginate(
            page, current_app.config['CARDS_PER_PAGE'], False
        )
        next_url = url_for('classroom.show_classroom', page=classrooms.next_num) if classrooms.has_next else None
        prev_url = url_for('classroom.show_classroom', page=classrooms.prev_num) if classrooms.has_prev else None

        return render_template('classroom/list_classrooms.html', title=f'Classrooms - {current_user.username}',
                               classrooms=classrooms.items, next_url=next_url,
                               prev_url=prev_url)
    # Classroom for Admins
    # Classroom for teachers
    if classroom_id:
        classroom = Classroom.query.filter_by(id=classroom_id).first()
        course_items = Coursework.query.filter_by(classroom_id=classroom.id).filter_by(creator_id=classroom.creator_id).all()
        course_items = [item for course_item in course_items for item in course_item.items]
        course_items = [(Coursework.query.filter_by(id=item.coursework_id).first().name, item, User.query.filter_by(id=item.student_id).first().username) for item in course_items]
        return render_template('classroom/classroom_detail.html', title=f'Classroom - {classroom.name}', classroom=classroom, course_items=course_items)

    page = request.args.get('page', 1, type=int)
    classrooms = Classroom.query.filter_by(creator_id=current_user.id).paginate(
        page, current_app.config['CARDS_PER_PAGE'], False
    )
    next_url = url_for('classroom.show_classroom', page=classrooms.next_num) if classrooms.has_next else None
    prev_url = url_for('classroom.show_classroom', page=classrooms.prev_num) if classrooms.has_prev else None

    return render_template('classroom/list_classrooms.html', title=f'Classrooms - {current_user.username}',
                           classrooms=classrooms.items, next_url=next_url,
                           prev_url=prev_url)



@bp.route('/add', methods=['GET', 'POST'])
@login_required
@role_required('Teacher')
def add_classroom():
    # TODO: Permission for Teachers
    form = AddClassroomForm()
    form.subject.choices = [(_subject.id, _subject.name) for _subject in Subject.query.order_by('name')]
    if form.validate_on_submit():
        classroom = Classroom(
            name = form.name.data,
            description = form.description.data,
            subject = form.subject.data,
            term = form.term.data,
            year = form.year.data,
            time = form.time.data,
            active = form.active.data,
            creator_id = current_user.id
        )
        db.session.add(classroom)
        db.session.commit()
        flash('Your new classroom has been saved.')
        return redirect(url_for('classroom.show_classroom', classroom_id=classroom.id))
    return render_template('classroom/add_classroom.html', title='Add Classroom', form=form)


@bp.route('/edit/<int:classroom_id>', methods=['GET', 'POST'])
@login_required
@role_required('Teacher')
def edit_classroom(classroom_id):
    classroom = Classroom.query.filter_by(id=classroom_id).first_or_404()
    form = AddClassroomForm()
    form.subject.choices = [(_subject.id, _subject.name) for _subject in Subject.query.order_by('name')]
    if form.validate_on_submit():
        classroom.name = form.name.data
        classroom.description = form.description.data
        classroom.subject = form.subject.data
        classroom.term = form.term.data
        classroom.year = form.year.data
        classroom.time = form.time.data
        classroom.active = form.active.data

        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('classroom.show_classroom', id=classroom.id))
    elif request.method == 'GET':
        form.name.data = classroom.name
        form.description.data = classroom.description
        form.subject.data = classroom.subject
        form.term.data = classroom.term
        form.year.data = classroom.year
        form.time.data = classroom.time
        form.active.data = classroom.active
    return render_template('classroom/edit_classroom.html', title='Edit Classroom',
                           form=form)


@bp.route('/add_classroom/<int:classroom_id>', methods=['GET', 'POST'])
@login_required
@role_required('Teacher')
def add_student_to_classroom(classroom_id):
    form = AddStudentForm()
    classroom = Classroom.query.filter_by(id=classroom_id).first_or_404()
    in_class_students = [student.id for student in classroom.students.all()]
    results = db.session.query(User).filter(User.role_id==1).filter(User.id.notin_(in_class_students)).all()
    form.student.choices = [(student.id, student.username) for student in results]
    # form.student.choices = [(student.id, student.username) for student in User.query.filter_by(role_id=1).filter(id.notin_(in_class_students)).order_by('name')]
    if request.method == 'POST':
        student_name = form.student.data
        student = User.query.filter_by(id=int(student_name)).first_or_404()
        classroom.add_student(student)
        
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('classroom.show_classroom', classroom_id=classroom.id))
    return render_template('classroom/add_student_to_classroom.html', title='Add Student to Classroom',
                           form=form)


@bp.route('/remove_student_classroom/<int:classroom_id>/<int:student_id>', methods=['DELETE'])
@login_required
@role_required('Teacher')
def remove_student_from_classroom(classroom_id, student_id):
    classroom = Classroom.query.filter_by(id=classroom_id).first_or_404()
    user = User.query.filter_by(id=student_id).first_or_404()
    # Delete logic
    classroom.remove_student(user)
    db.session.commit()
    return jsonify({
        'status': 'success'
    }), 200

@bp.route('/add_grade/<int:classroom_id>/<int:student_id>', methods=['GET', 'POST'])
@login_required
@role_required('Teacher')
def add_grade(classroom_id, student_id):
    form = AddStudentGradeForm()
    classroom = Classroom.query.filter_by(id=classroom_id).first_or_404()
    form.coursework_item.choices = [(course_item.id, course_item.name) for course_item in Coursework.query.filter_by(classroom_id=classroom_id).filter_by(creator_id=classroom.creator_id).all()]
    if form.validate_on_submit():
        cousework_obj = CourseworkInstance(form.grade.data, form.date_occurred.data, datetime.now(), datetime.now(),
                                           form.graded.data, form.comments.data, classroom_id, student_id, current_user.id,
                                           form.coursework_item.data)
        db.session.add(cousework_obj)
        db.session.commit()
        return redirect(url_for('classroom.show_classroom', classroom_id=classroom.id))
    return render_template('classroom/add_student_grade.html', title='Add Grade for Student',
                           form=form)


@bp.route('/edit_grade/<int:coursework_item_id>', methods=['GET', 'POST'])
@login_required
@role_required('Teacher')
def edit_grade(coursework_item_id):
    # form = AddStudentGradeForm()
    # classroom = Classroom.query.filter_by(id=classroom_id).first_or_404()
    # form.coursework_item.choices = [(course_item.id, course_item.name) for course_item in Coursework.query.filter_by(classroom_id=classroom_id).filter_by(creator_id=classroom.creator_id).all()]
    # if form.validate_on_submit():
    #     cousework_obj = CourseworkInstance(form.grade.data, form.date_occurred.data, datetime.now(), datetime.now(),
    #                                        form.graded.data, form.comments.data, classroom_id, student_id, current_user.id,
    #                                        form.coursework_item.data)
    #     db.session.add(cousework_obj)
    #     db.session.commit()
    #     return redirect(url_for('classroom.show_classroom', classroom_id=classroom.id))
    return render_template('classroom/add_student_grade.html', title='Add Grade for Student',
                           form=form)


@bp.route('/delete_grade/<int:coursework_item_id>', methods=['GET', 'POST'])
@login_required
@role_required('Teacher')
def delete_grade(coursework_item_id):
    # form = AddStudentGradeForm()
    # classroom = Classroom.query.filter_by(id=classroom_id).first_or_404()
    # form.coursework_item.choices = [(course_item.id, course_item.name) for course_item in Coursework.query.filter_by(classroom_id=classroom_id).filter_by(creator_id=classroom.creator_id).all()]
    # if form.validate_on_submit():
    #     cousework_obj = CourseworkInstance(form.grade.data, form.date_occurred.data, datetime.now(), datetime.now(),
    #                                        form.graded.data, form.comments.data, classroom_id, student_id, current_user.id,
    #                                        form.coursework_item.data)
    #     db.session.add(cousework_obj)
    #     db.session.commit()

app/templates/classroom/_classroom.html
    <div class="card">
        <img class="card-img-top" src="{{url_for('static', filename='Images/maths.jpg')}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{classroom.term}} - {{classroom.name}} - {{classroom.time}}</h5>
            <p class="card-text">{{classroom.description}}</p>
        </div>
        <div class="card-footer">
            <a href="{{url_for('classroom.show_classroom', classroom_id=classroom.id)}}">
                <small class="text-muted">Classroom Details</small>
            </a>
            <a href="{{url_for('classroom.edit_classroom', classroom_id=classroom.id)}}">
                <small class="text-muted">Edit Classroom</small>
            </a>
        </div>
    </div>

app/templates/classroom/add_classroom.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Add Classroom</h1>
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/classroom/add_student_grade.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Add Student Grade</h1>
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/classroom/add_student_to_classroom.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Add Student to Classroom</h1>
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/classroom/classroom_detail.html
{% extends "base.html" %}

{% block app_content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ classroom.name }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{{url_for('classroom.add_student_to_classroom', classroom_id=classroom.id)}}"><button
                    class="btn btn-sm btn-outline-secondary">Add Student</button></a>
        </div>
    </div>
</div>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <h1 class="h3">Roster</h1>
            <table class="table table-bordered table-hover" id="tab_logic">
                <thead>
                    <tr>
                        <th class="text-center">
                            #
                        </th>
                        <th class="text-center">
                            Name
                        </th>
                        <th class="text-center">
                            Current Grade
                        </th>
                        <th class="text-center">
                            Add Grade
                        </th>
                        <th class="text-center">
                            Remove Student
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in classroom.students %}
                    <tr id="{{student.id}}">
                        <td>{{student.id}}</td>
                        <td>{{student.username}}</td>
                        <td>90</td>
                        <td><a href="{{url_for('classroom.add_grade', student_id=student.id, classroom_id=classroom.id)}}">Add Grade</a></td>
                        <td><a data-key="{{student.id}}" class="remove_student" href="{{url_for('classroom.remove_student_from_classroom', classroom_id=classroom.id, student_id=student.id)}}">Remove Student</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<!-- Must Show Gradebook -->
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <h1 class="h3">Gradebook</h1>
            <table class="table table-bordered table-hover" id="tab_logic">
                <thead>
                    <tr>
                        <th class="text-center">
                            Coursework Item #
                        </th>
                        <th class="text-center">
                            Coursework Name
                        </th>
                        <th class="text-center">
                            Student Name
                        </th>
                        <th class="text-center">
                            Date Taken
                        </th>
                        <th class="text-center">
                            Updated At
                        </th>
                        <th class="text-center">
                            Grade
                        </th>
                        <th class="text-center">
                            Edit Coursework Item
                        </th>
                        <th class="text-center">
                            Delete Coursework Item
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for coursework_name, coursework_item, student_name in course_items %}
                    <tr id="{{coursework_item.id}}">
                        <td>{{ coursework_item.id }}</td>
                        <td>{{ coursework_name }}</td>
                        <td>{{ student_name }}</td>
                        <td>{{ moment(coursework_item.date_occurred).calendar() }}</td>
                        <td>{{ moment(coursework_item.updated_at).calendar() }}</td>
                        <td>{{ coursework_item.value }}</td>
                        <td><a
                                href="{{url_for('classroom.edit_grade', coursework_item_id=coursework_item.id)}}">Edit
                                Grade</a></td>
                        <td><a data-key="{{coursework_item.id}}" class="delete_student"
                                href="{{url_for('classroom.delete_grade', coursework_item_id=coursework_item.id)}}">Remove
                                Grade</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}

$(document).ready(function () {
    $(".remove_student").click(function (e) {
        e.preventDefault()
    }
});
{% endblock %}

app/templates/classroom/edit_classroom.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Edit Classroom</h1>
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/classroom/list_classrooms.html
{% extends "base.html" %}

{% block app_content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Classes</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="{{url_for('classroom.add_classroom')}}"><button class="btn btn-sm btn-outline-secondary">Add Class</button></a>
        </div>

        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Subject
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
</div>

<div class="card-deck">
{% for classroom in classrooms %}
{% include 'classroom/_classroom.html' %}
{% endfor %}
</div>

<nav aria-label="...">
    <ul class="pager">
        <li class="previous{% if not prev_url %} disabled{% endif %}">
            <a href="{{ prev_url or '#' }}">
                <span aria-hidden="true">&larr;</span> Newer posts 
            </a>
        </li>
        <li class="next{% if not next_url %} disabled{% endif %}">
            <a href="{{ next_url or '#' }}"> Older posts <span aria-hidden="true">&rarr;</span>
            </a>
        </li>
    </ul>
</nav>
{% endblock %}